# Generated by Django 2.2.6 on 2020-10-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='女', max_length=32)),
                ('c_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkTimes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_month', models.CharField(max_length=64, unique=True)),
                ('worker', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('status_info', models.CharField(choices=[('yes', '完成'), ('no', '未完成')], default='未完成', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('function_name', models.CharField(max_length=128)),
                ('dev_front', models.CharField(max_length=32)),
                ('dev_back', models.CharField(max_length=32)),
                ('dev_h5', models.CharField(max_length=32)),
                ('dev_native', models.CharField(max_length=32)),
                ('tester', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('test_status', models.CharField(choices=[('yes', '是'), ('no', '否')], default='否', max_length=32)),
                ('test_env', models.CharField(max_length=16)),
                ('uat_env', models.CharField(max_length=16)),
                ('question_remark', models.CharField(max_length=256, null=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iyb.WorkTimes')),
            ],
        ),
    ]
